/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ShoppingMenu;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Toolkit;
import static Login.CustomerLogin.name;

/**
 *
 * @author ASUS
 */
public class PT extends javax.swing.JFrame {

    /**
     */
    int item;
    public static double sum_price = 0;

    public PT() {
        initComponents();
        SetIcon();
    }

    private void SetIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons8-card-payment-30.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        plus = new javax.swing.JButton();
        lb = new javax.swing.JLabel();
        minus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Names = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        payButton = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lb_sumprice = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTextField1.setText("jTextField1");

        jLabel2.setText("jLael2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jTextPane1.setEditable(false);
        jScrollPane4.setViewportView(jTextPane1);

        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        lb.setText("0");

        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Customer:");

        Names.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Names.setText("Null");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShoppingMenu/icons8-add-shopping-cart-30.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShoppingMenu/icons8-clear-shopping-cart-30.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Product:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Chocolate bar", "15.0"},
                {"Milk", "42.5"},
                {"Pork guts", "8.5"},
                {"Condom", "29.5"},
                {"Chicken", "5.0"},
                {"Shampoo", "80.25"}
            },
            new String [] {
                "item", "price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setToolTipText("");
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Names))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(add)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(minus)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Names))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plus)
                    .addComponent(lb)
                    .addComponent(minus)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(add)
                .addGap(16, 16, 16))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        payButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        payButton.setText("Pay");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Total Price : ");

        lb_sumprice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_sumprice.setText("0");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShoppingMenu/icons8-shopping-cart-30.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShoppingMenu/icons8-clear-shopping-cart-30.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "item", "Qty", "price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(payButton)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(delete))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_sumprice)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payButton)
                    .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lb_sumprice))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        // TODO add your handling code here:
        //gide
        item++;
        lb.setText(Integer.toString(item));
    }//GEN-LAST:event_plusActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        // TODO add your handling code here:
        //gide
        if (item > 0) {
            item--;
            lb.setText(Integer.toString(item));
        }

    }//GEN-LAST:event_minusActionPerformed

    int selected;
    double sumPricePerItem;

    private double sumPrice() {
        sumPricePerItem = 0;
        sumPricePerItem = Double.valueOf(item) * Double.parseDouble(jTable2.getValueAt(selected, 1).toString());
        return sumPricePerItem;

    }
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

        // Display item 
        selected = jTable2.getSelectedRow();
        String s = String.valueOf(jTable2.getValueAt(selected, 0));
        jTextPane1.setText(s);

    }//GEN-LAST:event_jTable2MouseClicked

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        //Pay here
        //IT
        Bill bill = new Bill();
        bill.show();
        String totalPrice = lb_sumprice.getText();
        int NumRow2 = jTable1.getRowCount();
        bill.textArea.setText("\tMai Saduak Sue\n");
        bill.textArea.setText(bill.textArea.getText() + "\t       minimart\n");
        bill.textArea.setText(bill.textArea.getText() + "----------------------------------------------------------------\n");
        bill.textArea.setText(bill.textArea.getText() + "   Item \tQty \tPrice \n");
        bill.textArea.setText(bill.textArea.getText() + "----------------------------------------------------------------\n");
        for (int i = 0; i < NumRow2; i++) {
            String item = String.valueOf(jTable1.getValueAt(i, 0).toString());
            String q = String.valueOf(jTable1.getValueAt(i, 1).toString());
            String p = String.valueOf(jTable1.getValueAt(i, 2).toString());
            bill.textArea.setText(bill.textArea.getText() + item + "\t" + q + "\t" + p + "\n");
        }
        bill.textArea.setText(bill.textArea.getText() + "----------------------------------------------------------------\n");

        bill.textArea.setText(bill.textArea.getText() + "Costumer: " + name + "\n");

        bill.textArea.setText(bill.textArea.getText() + "----------------------------------------------------------------\n");

        bill.textArea.setText(bill.textArea.getText() + "Total Price : " + totalPrice + "\n");

        bill.textArea.setText(bill.textArea.getText() + "\t\tCashier\n");
        jTable1.setModel(new DefaultTableModel(null, new String[]{"item", "Qty.", "price"}));
    }//GEN-LAST:event_payButtonActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        //art
        // Add item to Cart here
        int numRow = jTable1.getRowCount();

        if (item > 0) {

            DefaultTableModel delete = (DefaultTableModel) jTable1.getModel();

            int IsSameValue = 0;
            int get_i = 0;
            for (int i = 0; i < numRow; i++) {
                if (jTable2.getModel().getValueAt(selected, 0) == jTable1.getModel().getValueAt(i, 0)) {
                    IsSameValue++;
                    get_i = i;
                }
            }

            System.out.println("C : " + IsSameValue);
            if (IsSameValue == 0) {

                AddRowToJTable(new Object[]{
                    jTable2.getModel().getValueAt(selected, 0),
                    lb.getText(),
                    sumPrice()

                }
                );
            } else if (IsSameValue > 0) {
                System.out.println("get_i : " + get_i);
                System.out.println("loop get_i : " + get_i);
                if (jTable2.getModel().getValueAt(selected, 0) == jTable1.getModel().getValueAt(get_i, 0)) {
                    System.out.println("xxx");
                    int numJT2 = Integer.valueOf(lb.getText().toString());
                    double priceJT2 = Double.valueOf(jTable2.getValueAt(selected, 1).toString());
                    double SpJT2 = Double.valueOf(numJT2) * priceJT2;
                    System.out.println("n2 : " + numJT2);
                    System.out.println("p2 : " + priceJT2);
                    System.out.println("SUMp2 = numJT2 *  priceJT2 : " + SpJT2);

                    System.out.println("-----------------------");

                    int numJT1 = Integer.valueOf(jTable1.getValueAt(get_i, 1).toString());
                    double priceJT1 = Double.valueOf(jTable1.getValueAt(get_i, 2).toString());

                    System.out.println("numJT1 : " + numJT1);
                    System.out.println("priceJT1 : " + priceJT1);

                    System.out.println("-----------------------");

                    int dfQtyJT1 = numJT2 + numJT1;
                    double dfPriceJT1 = SpJT2 + priceJT1;

                    System.out.println("dfQtyJT1 : " + dfQtyJT1);
                    System.out.println("dfPriceJT1 : " + dfPriceJT1);

                    jTable1.setValueAt(jTable2.getModel().getValueAt(selected, 0), get_i, 0);
                    jTable1.setValueAt(dfQtyJT1, get_i, 1);
                    jTable1.setValueAt(dfPriceJT1, get_i, 2);
                }

            }

            JOptionPane.showMessageDialog(null, "Add successful !! ");

        } else {
            JOptionPane.showMessageDialog(null, "Choose item and Input value of item !! ");
        }

        item = 0;
        lb.setText("0");

        //Show Total price on label
        int NumRow = jTable1.getRowCount();
        double Total = 0;
        for (int i = 0; i < NumRow; i++) {
            double Value = Double.valueOf(jTable1.getValueAt(i, 2).toString());
            Total += Value;
            lb_sumprice.setText(Double.toString(Total));
        }
    }//GEN-LAST:event_addActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        //ter
        DefaultTableModel delete = (DefaultTableModel) jTable1.getModel();
        //delete row
        if (jTable1.getSelectedRowCount() == 1) {
            delete.removeRow(jTable1.getSelectedRow());
            int NumRow = jTable1.getRowCount();
            if (jTable1.getRowCount() == 0) {
                lb_sumprice.setText("0");
            } else {
                double Total = 0;
                for (int i = 0; i < NumRow; i++) {
                    double Value = Double.valueOf(jTable1.getValueAt(i, 2).toString());
                    Total += Value;
                    lb_sumprice.setText(Double.toString(Total));
                }
            }
        } else {
            if (jTable1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "It's empty !!  ");
            } else if (jTable1.getSelectedRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "select any row for delete !!");
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the comme { double Total = 0; for (int i = 0; i < NumRow;
     * i++) { double Value = Double.valueOf(jTable1.getValueAt(i,
     * 1).toString()); Total += Value;
     * lb_sumprice.setText(Double.toString(Total)); } } } else {
     * if(jTable1.getRowCount() == 0){ JOptionPane.showMessageDialog(this, "It's
     * empty !! "); else if (jTable1.getSelectedRowCount() == 0) {
     * JOptionPane.showMessageDialog(this, "select any row for delete !!"); } }
     * } } * /** @paand line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PT().setVisible(true);
            }
        });
    }

    public static void AddRowToJTable(Object[] dataRow) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(dataRow);
    }
//  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Names;
    private javax.swing.JButton add;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private static javax.swing.JTable jTable1;
    private static javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lb;
    public static javax.swing.JLabel lb_sumprice;
    private javax.swing.JButton minus;
    private javax.swing.JButton payButton;
    private javax.swing.JButton plus;
    // End of variables declaration//GEN-END:variables
}
